# dinitctl
# Autogenerated from man page /home/me/.local/share/man/man8/dinitctl.8
set -l commands start stop status is-started is-failed restart wake release unpin unload reload list shutdown add-dep rm-dep enable disable trigger untrigger setenv catlog signal
complete -c dinitctl -f
complete -c dinitctl -n "not __fish_seen_subcommand_from $commands" \
    -a "$commands"
complete -c dinitctl -l help -d 'Display brief help text and then exit'
complete -c dinitctl -l version -d 'Display version and then exit'
complete -c dinitctl -s s -l system -d 'Control the system init process (this is the default when run as root)'
complete -c dinitctl -s u -l user -d 'Control the user init process (this is the default when not run as root)'
complete -c dinitctl -l socket-path -s p -d 'Specify the path to the socket used for communicating with the service manage…'
complete -c dinitctl -l use-passed-cfd -d 'Instead of attempting to open a socket connection to the service daemon, use …'
complete -c dinitctl -l quiet -d 'Suppress status output, except for errors'
complete -c dinitctl -l offline -s o -d 'Work "offline", without communicating with the dinit daemon'
complete -c dinitctl -l services-dir -s d -d 'Specifies dir as the directory containing service description files (can be g…'
complete -c dinitctl -l no-wait -d 'Do not wait for issued command to complete; exit immediately'
complete -c dinitctl -l pin -d 'Pin the service in the requested state'
complete -c dinitctl -l force -d 'Stop the service even if it will require stopping other services which depend…'
complete -c dinitctl -l ignore-unstarted -d 'If the service is not started or doesn\'t exist, ignore the command and return…'
complete -c dinitctl -l clear -d 'Clear the log buffer for the service after displaying it'

