[keepass]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa4xrXNa_MFrh5P0QzrvjOkZB2NO8bfzoEAucqhrVdYYUKIuQ_I1gsKzmtCXzRKh3k9sq8PvWD27D6dZ9z86glkEvR_2Lc3dV9RDOivnrZOj3krUH0jltu1aFAABIuLokgDOOFMVyT8yh9F-GSy_rXvxofYqWwaCgYKATASARASFQEjDvL9pPilpW2uHLjPxBrGIg1OwQ0165","token_type":"Bearer","refresh_token":"1//06HiD7uScE6XeCgYIARAAGAYSNwF-L9IrkIzWrJhIO0hP1Ep8ONKlCTxYVLU3Ilbuh65ogZx2XekOdMbPEatKNySVo6WgQrzRALY","expiry":"2022-10-11T18:05:02.585295861-07:00"}
team_drive = 
root_folder_id = 1UDlcxb7Q_-bLdU3et7zyN8w4-8Nk4sKi
use_trash = false

