[keepass]
type = drive
scope = drive
token = {"access_token":"ya29.a0Aa4xrXPZ88tc0cuv0FPGbVzeetI4-CJT1H_SY65dwhTrTcuExL9FKBYCoZnG2e9edEL7uXpOt5KObTpXzSl5ATFmkwdpmme12tBix1cUjc0VDpJjcfVvpavopMbbFSyO87alEjbVzvFnAefDVEBMDlxR4p8b1QaCgYKATASARASFQEjDvL9rn0_-pv6X_3jXc1l48z8xQ0165","token_type":"Bearer","refresh_token":"1//06HiD7uScE6XeCgYIARAAGAYSNwF-L9IrkIzWrJhIO0hP1Ep8ONKlCTxYVLU3Ilbuh65ogZx2XekOdMbPEatKNySVo6WgQrzRALY","expiry":"2022-10-11T16:02:48.019999175-07:00"}
team_drive = 
root_folder_id = 1UDlcxb7Q_-bLdU3et7zyN8w4-8Nk4sKi
use_trash = false

